const array = [
  { numberCard: "2 of Hearts", number: 2, suit: "Hearts" },
  { numberCard: "3 of Hearts", number: 3, suit: "Hearts" },
  { numberCard: "4 of Hearts", number: 4, suit: "Hearts" },
  { numberCard: "5 of Hearts", number: 5, suit: "Hearts" },
  { numberCard: "6 of Hearts", number: 6, suit: "Hearts" },
  { numberCard: "7 of Hearts", number: 7, suit: "Hearts" },
  { numberCard: "8 of Hearts", number: 8, suit: "Hearts" },
  { numberCard: "9 of Hearts", number: 9, suit: "Hearts" },
  { numberCard: "10 of Hearts", number: 10, suit: "Hearts" },
  { numberCard: "Jack of Hearts", number: 11, suit: "Hearts" },
  { numberCard: "Queen of Hearts", number: 12, suit: "Hearts" },
  { numberCard: "King of Hearts", number: 13, suit: "Hearts" },
  { numberCard: "Ace of Hearts", number: 14, suit: "Hearts" },

  { numberCard: "2 of Diamonds", number: 2, suit: "Diamonds" },
  { numberCard: "3 of Diamonds", number: 3, suit: "Diamonds" },
  { numberCard: "4 of Diamonds", number: 4, suit: "Diamonds" },
  { numberCard: "5 of Diamonds", number: 5, suit: "Diamonds" },
  { numberCard: "6 of Diamonds", number: 6, suit: "Diamonds" },
  { numberCard: "7 of Diamonds", number: 7, suit: "Diamonds" },
  { numberCard: "8 of Diamonds", number: 8, suit: "Diamonds" },
  { numberCard: "9 of Diamonds", number: 9, suit: "Diamonds" },
  { numberCard: "10 of Diamonds", number: 10, suit: "Diamonds" },
  { numberCard: "Jack of Diamonds", number: 11, suit: "Diamonds" },
  { numberCard: "Queen of Diamonds", number: 12, suit: "Diamonds" },
  { numberCard: "King of Diamonds", number: 13, suit: "Diamonds" },
  { numberCard: "Ace of Diamonds", number: 14, suit: "Diamonds" },

  { numberCard: "2 of Clubs", number: 2, suit: "Clubs" },
  { numberCard: "3 of Clubs", number: 3, suit: "Clubs" },
  { numberCard: "4 of Clubs", number: 4, suit: "Clubs" },
  { numberCard: "5 of Clubs", number: 5, suit: "Clubs" },
  { numberCard: "6 of Clubs", number: 6, suit: "Clubs" },
  { numberCard: "7 of Clubs", number: 7, suit: "Clubs" },
  { numberCard: "8 of Clubs", number: 8, suit: "Clubs" },
  { numberCard: "9 of Clubs", number: 9, suit: "Clubs" },
  { numberCard: "10 of Clubs", number: 10, suit: "Clubs" },
  { numberCard: "Jack of Clubs", number: 11, suit: "Clubs" },
  { numberCard: "Queen of Clubs", number: 12, suit: "Clubs" },
  { numberCard: "King of Clubs", number: 13, suit: "Clubs" },
  { numberCard: "Ace of Clubs", number: 14, suit: "Clubs" },

  { numberCard: "2 of Spades", number: 2, suit: "Spades" },
  { numberCard: "3 of Spades", number: 3, suit: "Spades" },
  { numberCard: "4 of Spades", number: 4, suit: "Spades" },
  { numberCard: "5 of Spades", number: 5, suit: "Spades" },
  { numberCard: "6 of Spades", number: 6, suit: "Spades" },
  { numberCard: "7 of Spades", number: 7, suit: "Spades" },
  { numberCard: "8 of Spades", number: 8, suit: "Spades" },
  { numberCard: "9 of Spades", number: 9, suit: "Spades" },
  { numberCard: "10 of Spades", number: 10, suit: "Spades" },
  { numberCard: "Jack of Spades", number: 11, suit: "Spades" },
  { numberCard: "Queen of Spades", number: 12, suit: "Spades" },
  { numberCard: "King of Spades", number: 13, suit: "Spades" },
  { numberCard: "Ace of Spades", number: 14, suit: "Spades" },
];

export { array } from "/JS/numbercards.js";
